// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0i6WpQXf3roaXxqy1neJy0E3ZKNjEY6g',
    appId: '1:864898302801:web:1c4ec8188d6e48a679c970',
    messagingSenderId: '864898302801',
    projectId: 'expert-ditonton',
    authDomain: 'expert-ditonton.firebaseapp.com',
    storageBucket: 'expert-ditonton.appspot.com',
    measurementId: 'G-D4YNVYN94T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwpN1goQPAoO5WvImX4cgnrISMMb4dFTQ',
    appId: '1:864898302801:android:bd0bdc97ada4031579c970',
    messagingSenderId: '864898302801',
    projectId: 'expert-ditonton',
    storageBucket: 'expert-ditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-kRSJLX4RONMZSSh_noFs8iyxOQqVglQ',
    appId: '1:864898302801:ios:c73506f2cc564d8c79c970',
    messagingSenderId: '864898302801',
    projectId: 'expert-ditonton',
    storageBucket: 'expert-ditonton.appspot.com',
    iosClientId: '864898302801-i8tv898jmn9d7vqsdubhb0qliv1u6ib5.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
